package com.cloudesire.platform.apiclient.dto.model.dto;

import com.cloudesire.platform.apiclient.dto.model.enums.InvoiceStatus;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.cloudesire.platform.apiclient.dto.model.enums.InvoiceOperationType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import javax.validation.Valid;
import javax.validation.constraints.NotNull;
import java.math.BigDecimal;
import java.util.Date;
import java.util.EnumSet;
import java.util.List;
import java.util.Objects;
import java.util.Set;

@ApiModel( "An invoice generated by the platform after a customer order" )
public class InvoiceDTO extends BaseInvoiceDTO
{
    @NotNull
    @ApiModelProperty( value = "The amount to be paid", readOnly = true )
    protected VATPriceDTO total;

    @Valid
    @ApiModelProperty( value = "Who will pay the invoice", readOnly = true )
    private UrlEntityDTO nominee;

    @ApiModelProperty( value = "If the invoice emission and payment is handled by vendor/reseller or by the platform", readOnly = true )
    private boolean selfBilled = false;

    @ApiModelProperty( value = "If this invoice is subject to the Italian electronic document tax", readOnly = true )
    private boolean stampDuty = false;

    @NotNull
    @ApiModelProperty( value = "The order type this invoice refers to", readOnly = true, allowableValues = "NORMAL, TRIAL, SANDBOX" )
    private String type = "NORMAL";

    @NotNull
    @ApiModelProperty( value = "The product name this invoice refers to", readOnly = true )
    private String product = "N/A";

    @NotNull
    @ApiModelProperty( value = "The ProductVersion name this invoice refers to", readOnly = true )
    private String productVersion = "N/A";

    @JsonInclude ( JsonInclude.Include.NON_EMPTY )
    @ApiModelProperty( value = "A reference of a successfull payment", readOnly = true )
    private String paymentReference;

    @JsonInclude ( JsonInclude.Include.NON_EMPTY )
    @ApiModelProperty( value = "When the payment of the invoice has completed successfully", readOnly = true )
    private Date paymentReceived;

    @Valid
    private UrlEntityDTO subscription;

    @ApiModelProperty( value = "The operations that can be executed by the current user on the invoice", readOnly = true )
    private Set<InvoiceOperationType> availableOperations = EnumSet.noneOf( InvoiceOperationType.class );

    @ApiModelProperty( value = "The reference to a PDF version of the invoice", readOnly = true )
    private String remoteId;

    @ApiModelProperty( value = "The quota that received the platform owner when the invoice has been issued", readOnly = true )
    private BigDecimal revenueSharingQuota;

    @NotNull
    @ApiModelProperty( "The billed lines of the invoice" )
    private List<OrderLineDTO> entries;

    @ApiModelProperty( value = "If the invoice has been generated by the vendor/reseller", readOnly = true )
    private Boolean cashed;

    private InvoiceStatus status;

    @Deprecated
    @ApiModelProperty( hidden = true )
    private BigDecimal totalPrice;

    @Deprecated
    @ApiModelProperty( hidden = true )
    private BigDecimal priceExcludingVAT;

    @Deprecated
    @ApiModelProperty( hidden = true )
    private BigDecimal vatSpunOff;

    @JsonIgnore
    public BigDecimal getIncome()
    {
        BigDecimal income = BigDecimal.ZERO;
        for ( OrderLineDTO entry : entries )
        {
            if ( ! entry.getType().isIncome() ) continue;
            income = income.add( entry.getSubtotal() );
        }
        return income;
    }

    public VATPriceDTO getTotal()
    {
        return total;
    }

    public void setTotal( VATPriceDTO total )
    {
        this.total = total;
    }

    public Date getPaymentReceived()
    {
        return paymentReceived;
    }

    public void setPaymentReceived( Date paymentReceived )
    {
        this.paymentReceived = paymentReceived;
    }

    public String getPaymentReference()
    {
        return paymentReference;
    }

    public void setPaymentReference( String paymentReference )
    {
        this.paymentReference = paymentReference;
    }

    public UrlEntityDTO getNominee()
    {
        return nominee;
    }

    public void setNominee( UrlEntityDTO nominee )
    {
        this.nominee = nominee;
    }

    public String getType()
    {
        return type;
    }

    public void setType( String type )
    {
        this.type = type;
    }

    public String getProduct()
    {
        return product;
    }

    public void setProduct( String what )
    {
        this.product = what;
    }

    public String getProductVersion()
    {
        return productVersion;
    }

    public void setProductVersion( String productVersion )
    {
        this.productVersion = productVersion;
    }

    public UrlEntityDTO getSubscription()
    {
        return subscription;
    }

    public void setSubscription( UrlEntityDTO subscription )
    {
        this.subscription = subscription;
    }

    public Set<InvoiceOperationType> getAvailableOperations()
    {
        return availableOperations;
    }

    public void setAvailableOperations( Set<InvoiceOperationType> availableOperations )
    {
        this.availableOperations = availableOperations;
    }

    public boolean isSelfBilled()
    {
        return selfBilled;
    }

    public void setSelfBilled( boolean selfBilled )
    {
        this.selfBilled = selfBilled;
    }

    public boolean isStampDuty()
    {
        return stampDuty;
    }

    public void setStampDuty( boolean stampDuty )
    {
        this.stampDuty = stampDuty;
    }

    @Deprecated
    public String getRemoteInvoiceId()
    {
        return remoteId;
    }

    public String getRemoteId()
    {
        return remoteId;
    }

    public void setRemoteId( String remoteId )
    {
        this.remoteId = remoteId;
    }

    public BigDecimal getRevenueSharingQuota()
    {
        return revenueSharingQuota;
    }

    public void setRevenueSharingQuota( BigDecimal revenueSharingQuota )
    {
        this.revenueSharingQuota = revenueSharingQuota;
    }

    @Deprecated
    public BigDecimal getTotalPrice()
    {
        return totalPrice;
    }

    @Deprecated
    public void setTotalPrice( BigDecimal totalPrice )
    {
        this.totalPrice = totalPrice;
    }

    @Deprecated
    public BigDecimal getPriceExcludingVAT()
    {
        return priceExcludingVAT;
    }

    @Deprecated
    public void setPriceExcludingVAT( BigDecimal priceExcludingVAT )
    {
        this.priceExcludingVAT = priceExcludingVAT;
    }

    @Deprecated
    public BigDecimal getVatSpunOff()
    {
        return vatSpunOff;
    }

    @Deprecated
    public void setVatSpunOff( BigDecimal vatSpunOff )
    {
        this.vatSpunOff = vatSpunOff;
    }

    @Deprecated
    public BigDecimal getVAT()
    {
        return total != null ? total.getVAT() : null;
    }

    public List<OrderLineDTO> getEntries()
    {
        return entries;
    }

    public void setEntries( List<OrderLineDTO> entries )
    {
        this.entries = entries;
    }

    public Boolean isCashed()
    {
        return cashed;
    }

    public void setCashed( Boolean cashed )
    {
        this.cashed = cashed;
    }

    public InvoiceStatus getStatus()
    {
        return status;
    }

    public void setStatus( InvoiceStatus status )
    {
        this.status = status;
    }

    /**
     * @deprecated by {@code getStatus()}
     */
    @Deprecated
    public boolean isPaid()
    {
        return status == InvoiceStatus.PAID;
    }

    @Override
    public boolean equals( Object o )
    {
        if ( this == o ) return true;
        if ( !( o instanceof InvoiceDTO ) ) return false;
        if ( !super.equals( o ) ) return false;
        InvoiceDTO that = (InvoiceDTO) o;
        return Objects.equals( total, that.total ) &&
                Objects.equals( paymentReference, that.paymentReference ) &&
                Objects.equals( paymentReceived, that.paymentReceived ) &&
                Objects.equals( remoteId, that.remoteId );
    }

    @Override
    public int hashCode()
    {
        return Objects.hash( super.hashCode(), total, paymentReference, paymentReceived, remoteId );
    }
}
